# Generated by Django 4.2.3 on 2023-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
